# Generated by Django 2.1 on 2018-07-15 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='positionsrelation',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
