# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-16 00:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Info', '0002_positionsrelation_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positionsrelation',
            name='ip',
            field=models.CharField(max_length=50),
        ),
    ]
