# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-16 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Info', '0003_auto_20180716_0817'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneConfigurationOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(blank=True, max_length=50, null=True)),
                ('Sip1_Enable', models.CharField(blank=True, max_length=50, null=True)),
                ('Sip1_DisplayName', models.CharField(blank=True, max_length=50, null=True)),
                ('Sip1_Label', models.CharField(blank=True, max_length=50, null=True)),
                ('Sip1_UserName', models.CharField(blank=True, max_length=50, null=True)),
                ('Sip1_AuthUserName', models.CharField(blank=True, max_length=50, null=True)),
                ('Sip1_AuthPassword', models.CharField(blank=True, max_length=50, null=True)),
                ('Sip1_RegistrarServer', models.CharField(blank=True, max_length=50, null=True)),
                ('Sip1_UseOutboundProxy', models.CharField(blank=True, max_length=50, null=True)),
                ('Sip1_OutboundProxy', models.CharField(blank=True, max_length=50, null=True)),
                ('Sip2_Enable', models.CharField(blank=True, max_length=50, null=True)),
                ('Sip2_DisplayName', models.CharField(blank=True, max_length=50, null=True)),
                ('Sip2_Label', models.CharField(blank=True, max_length=50, null=True)),
                ('Sip2_UserName', models.CharField(blank=True, max_length=50, null=True)),
                ('Sip2_AuthUserName', models.CharField(blank=True, max_length=50, null=True)),
                ('Sip2_AuthPassword', models.CharField(blank=True, max_length=50, null=True)),
                ('Sip2_RegistrarServer', models.CharField(blank=True, max_length=50, null=True)),
                ('Sip2_UseOutboundProxy', models.CharField(blank=True, max_length=50, null=True)),
                ('Sip2_OutboundProxy', models.CharField(blank=True, max_length=50, null=True)),
                ('AdminPassword', models.CharField(blank=True, max_length=50, null=True)),
                ('AutopServerAddress', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'phone_configuration_options',
            },
        ),
    ]
