# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-16 10:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Info', '0004_phoneconfigurationoptions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phoneconfigurationoptions',
            name='Sip1_AuthUserName',
        ),
        migrations.RemoveField(
            model_name='phoneconfigurationoptions',
            name='Sip1_DisplayName',
        ),
        migrations.RemoveField(
            model_name='phoneconfigurationoptions',
            name='Sip1_Enable',
        ),
        migrations.RemoveField(
            model_name='phoneconfigurationoptions',
            name='Sip1_Label',
        ),
        migrations.RemoveField(
            model_name='phoneconfigurationoptions',
            name='Sip1_UserName',
        ),
        migrations.RemoveField(
            model_name='phoneconfigurationoptions',
            name='Sip2_AuthUserName',
        ),
        migrations.RemoveField(
            model_name='phoneconfigurationoptions',
            name='Sip2_DisplayName',
        ),
        migrations.RemoveField(
            model_name='phoneconfigurationoptions',
            name='Sip2_Enable',
        ),
        migrations.RemoveField(
            model_name='phoneconfigurationoptions',
            name='Sip2_Label',
        ),
        migrations.RemoveField(
            model_name='phoneconfigurationoptions',
            name='Sip2_UserName',
        ),
    ]
