# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-02 02:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webchat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_name', models.CharField(max_length=64)),
                ('from_user_id', models.IntegerField()),
                ('to_name', models.CharField(max_length=64)),
                ('to_user_id', models.IntegerField()),
                ('contact_type', models.CharField(max_length=64)),
                ('msg_content', models.CharField(max_length=10000)),
                ('msg_type', models.CharField(max_length=64)),
                ('head_img', models.CharField(max_length=64)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
