"""
Django settings for AutoInfo project.

Generated by 'django-admin startproject' using Django 1.11.7.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '!r%dbl8zn&q9n!fjx^%paz%)#(bk-zq7_g(y(rppazp6*o_azm'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['10.6.0.118', '0.0.0.0', '127.0.0.1','neup.jd.com']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'Info',
    'django_celery_beat',
    # 'Info_test',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'middleware.is_login.Is_login'
]

ROOT_URLCONF = 'AutoInfo.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'AutoInfo.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'Autoinfo',
        'USER': 'seven',
        'PASSWORD': 'icson@123',
        'HOST': '10.6.0.118',
        'PORT': '3306',
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

# TIME_ZONE = 'UTC'
TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/


LOGIN_URL = '/login/'
STATIC_URL = '/static/'
MEDIA_URL = '/media/'
# STATIC_ROOT = '/var/www/AutoInfo/static'
# STATIC_ROOT = '/home/AutoInfo/static'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
    os.path.join(BASE_DIR, "media"),
]

# Celery settings
# CELERY_DIR = '/home/AutoInfo/'

# CELERY_ENABLE_UTC = False
CELERY_TIMEZONE = 'Asia/Shanghai'



CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'

# CELERY_BROKER_URL = 'mongodb://10.6.0.149:27017/celery'
# CELERY_RESULT_BACKEND = 'mongodb://10.6.0.149:27017/celery'

CELERY_BROKER_URL = 'redis://10.6.0.118:6379/0'
CELERY_RESULT_BACKEND = 'redis://10.6.0.118:6379/0'

# CELERY_CELERYD_CONCURRENCY = 4  # 任务并发数

# CELERY_CELERYBEAT_SCHEDULE = {
#     "every-1-minute": {
#         'task': 'Info.tasks.add',
#         'schedule': crontab(minute='*/1'),
#         'args': (5, 6)
#     }
# }
# CELERY_CELERY_ROUTES = {  # 配置任务的先后顺序
#     'Info.tasks.add': {'queue': 'for_add', 'router_key': 'for_add'},
#     'Info.tasks.reboot_phone': {'queue': 'for_reboot_phone', 'router_key': 'for_reboot_phone'},
#     'Info.tasks.crontab_reboot': {'queue': 'for_crontab_reboot', 'router_key': 'for_crontab_reboot'},
# }

