# Generated by Django 2.1 on 2018-07-16 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Info', '0002_positionsrelation_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneConfigurationOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(blank=True, max_length=50, null=True)),
                ('Sip1_AuthPassword', models.CharField(blank=True, max_length=50, null=True)),
                ('Sip1_RegistrarServer', models.CharField(blank=True, max_length=50, null=True)),
                ('Sip1_UseOutboundProxy', models.CharField(blank=True, max_length=50, null=True)),
                ('Sip1_OutboundProxy', models.CharField(blank=True, max_length=50, null=True)),
                ('Sip2_AuthPassword', models.CharField(blank=True, max_length=50, null=True)),
                ('Sip2_RegistrarServer', models.CharField(blank=True, max_length=50, null=True)),
                ('Sip2_UseOutboundProxy', models.CharField(blank=True, max_length=50, null=True)),
                ('Sip2_OutboundProxy', models.CharField(blank=True, max_length=50, null=True)),
                ('AdminPassword', models.CharField(blank=True, max_length=50, null=True)),
                ('AutopServerAddress', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'phone_configuration_options',
            },
        ),
    ]
