# Generated by Django 2.1 on 2018-07-17 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Info', '0008_phoneconfigurationoptions_sip1_enable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phoneconfigurationoptions',
            name='Sip1_Enable',
        ),
        migrations.RemoveField(
            model_name='phoneconfigurationoptions',
            name='Sip1_UseOutboundProxy',
        ),
        migrations.RemoveField(
            model_name='phoneconfigurationoptions',
            name='Sip2_Enable',
        ),
        migrations.RemoveField(
            model_name='phoneconfigurationoptions',
            name='Sip2_UseOutboundProxy',
        ),
    ]
