# Generated by Django 2.1 on 2018-07-28 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Info', '0015_auto_20180717_0748'),
    ]

    operations = [
        migrations.AddField(
            model_name='phoneconfigurationoptions',
            name='Sip1_AutoAnswerEnable',
            field=models.CharField(choices=[('true', '启用'), ('false', '禁用')], default='false', max_length=32),
        ),
        migrations.AddField(
            model_name='phoneconfigurationoptions',
            name='Sip2_AutoAnswerEnable',
            field=models.CharField(choices=[('true', '启用'), ('false', '禁用')], default='false', max_length=32),
        ),
        migrations.AlterField(
            model_name='phoneconfigurationoptions',
            name='Sip1_Enable',
            field=models.CharField(choices=[('Enabled', '启用'), ('Disabled', '禁用')], default='Enabled', max_length=32),
        ),
        migrations.AlterField(
            model_name='phoneconfigurationoptions',
            name='Sip1_UseOutboundProxy',
            field=models.CharField(choices=[('Enabled', '启用'), ('Disabled', '禁用')], default='Enabled', max_length=32),
        ),
    ]
