# Generated by Django 2.1 on 2018-07-17 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Info', '0006_auto_20180717_0733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phoneconfigurationoptions',
            name='Sip1_Enable',
        ),
    ]
