# Generated by Django 2.1 on 2018-07-17 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Info', '0012_auto_20180717_0746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phoneconfigurationoptions',
            name='Sip2_UseOutboundProxy',
        ),
    ]
