# Generated by Django 2.1 on 2018-07-17 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Info', '0013_remove_phoneconfigurationoptions_sip2_useoutboundproxy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phoneconfigurationoptions',
            name='Sip1_Enable',
        ),
        migrations.RemoveField(
            model_name='phoneconfigurationoptions',
            name='Sip1_UseOutboundProxy',
        ),
        migrations.RemoveField(
            model_name='phoneconfigurationoptions',
            name='Sip2_Enable',
        ),
    ]
