# Generated by Django 2.1 on 2018-12-21 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Info', '0017_positionsrelation_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='positionsrelation',
            name='area',
        ),
    ]
