# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-10 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Info', '0018_remove_positionsrelation_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='CeleryTaskRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=50, null=True)),
                ('device_id', models.CharField(blank=True, max_length=50, null=True)),
                ('task_id', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'celery_task_record',
            },
        ),
    ]
