# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-10 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Info', '0019_celerytaskrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='celerytaskrecord',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='celerytaskrecord',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
