# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0002_article_head_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='head_img',
            field=models.ImageField(upload_to='uploads', verbose_name='文章标题图片'),
        ),
    ]
