# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 05:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0003_auto_20170808_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='_userprofile_friends_+', to='bbs.UserProfile'),
        ),
    ]
