# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-08 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0006_auto_20170902_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='head_img',
            field=models.ImageField(upload_to='media', verbose_name='文章标题图片'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='head_img',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
